// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx5Aj6PkQuBxbvtdxBH3YANoqZGi4G2JE',
    appId: '1:967007639924:web:a8806b3e0d3271aa653421',
    messagingSenderId: '967007639924',
    projectId: 'crmga-d817b',
    authDomain: 'crmga-d817b.firebaseapp.com',
    storageBucket: 'crmga-d817b.firebasestorage.app',
    measurementId: 'G-G5DTXDJ74M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2oUxDgXyh3_ZRxMkVwvajMaeaax1JV7A',
    appId: '1:967007639924:android:babb59094ad617ba653421',
    messagingSenderId: '967007639924',
    projectId: 'crmga-d817b',
    storageBucket: 'crmga-d817b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT3i2QTi6k7QMDP48RxWXJumlkIX_zczs',
    appId: '1:967007639924:ios:4b32cd9f7d6fc25b653421',
    messagingSenderId: '967007639924',
    projectId: 'crmga-d817b',
    storageBucket: 'crmga-d817b.firebasestorage.app',
    iosBundleId: 'com.example.crmgaApp',
  );
}
